// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaDDrS_jFq30uuDm6GpwFGKVrsas1kY34',
    appId: '1:812477328372:android:ec6e0035a6fb3d1a6827a1',
    messagingSenderId: '812477328372',
    projectId: 'io-box',
    databaseURL: 'https://io-box-default-rtdb.firebaseio.com',
    storageBucket: 'io-box.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0At2yKSoARRq3sB8QBspC327OTOkilZ0',
    appId: '1:812477328372:ios:8618f9ddfd11921a6827a1',
    messagingSenderId: '812477328372',
    projectId: 'io-box',
    databaseURL: 'https://io-box-default-rtdb.firebaseio.com',
    storageBucket: 'io-box.appspot.com',
    androidClientId: '812477328372-1fgs4pm2ld93ui1arebbsofpuckprofn.apps.googleusercontent.com',
    iosClientId: '812477328372-p45n4dsugka9psbpcrv91peeg2a61fnp.apps.googleusercontent.com',
    iosBundleId: 'com.IoBox.Uncle',
  );
}
